---
title: "About"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---


---

> Reducing infection once and floral: Examining the effects of different pollen diets on *in vitro* growth and attachment of *C. bombi*, a parasite of bumblebees.

---

### Methods:

1. Growth curves to observe and quantify *in vitro* swimming cell growth.

2. Attachment assay to observe and quantify *in vitro* attachment.

3. Transfect an episomal construct containing Nanoluciferase and a Hygromycin cassette for better quantitation in the presence of pollen.

4. Growth curve by plate reader to quantify *in vitro* swimming cell growth in the presence of pollen exines.

5. Attachment assay on the initial plating to observe and quantify *in vitro* attachment in the presence of pollen exines.

6. Wash attachment assay after 48 hours of attachment to observe and quantify how *in vitro* attachment is affected by the presence of pollen exines.

7. Proteomic analysis to observe different protein expression in swimming and adhered cells

---

### Publications (in progress)

[Genetic modification of the bee parasite *Crithidia bombi* for improved visualization and protein localization](https://www.biorxiv.org/content/10.1101/2024.01.18.576273v1)

---

#### Working in [Dr. Megan Povelones Lab](https://megpovelab.com/) at Villanova University

---

#### This material is based upon work supported by the National Science Foundation under grant number 2128223.

---



