---
title: "Measuring growth of swimming C. bombi cells in the presence of SF and BW pollen exines"
author: "fstclair"
date: "2024-03-01"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Determining the effect of sunflower pollen exines on swimming *C. bombi* cell growth.

---

#### Background

Our collaborators have found that sunflower pollen reduces *C. bombi* infection inside the bumblebee through an unknown mechanism ([Figueroa, L., 2023](https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/1365-2435.14320?casa_token=B8ZgWiM3CUUAAAAA%3Ap-wb7aqeD60s8_usDKbRK_kvtSCp3V5wFSpyuVN0kv8LKbRd97y5Wlrlcdfu8E9RxFtlc3vmKQXmxOk)). 

This experiment is an attempt to understand if *C. bombi* swimming cell growth is affected by the presence of SF exine media while using BW exine media and regular media as controls.


---

#### Description

Quantifying swimming *C. bombi* cell growth in the presence of BW or SF pollen exines over 72 hours to explore pollen effects on the growth of swimming cells.

*C. bombi* was transfected with an episomal construct containing Nanoluciferase (Nluc), a constitutively expressed Nluc reporter, and a Hygromycin cassette for selection.

Growth was measured in Relative Light Units (RLU) using a plate reader and normalized to the plate using a standard dilution series from 1E1 to 1E6 cells/well to capture cell density in cells/mL.

<br>

---


### Swimming cell growth with BW or SF pollen exines


```{r swimming_growth, echo=FALSE, message=FALSE}

# Libraries
library(ggplot2)
library(dplyr)

#upload data
sc <- read.csv("~/Desktop/Coding/workflowr/learning_workflowr/data/swimming.csv") #set data name

# Keep only 3 names
sc1 <- sc %>% 
  filter(treatment %in% c("Media", "BW Media", "SF Media")) 
  
#set colors
cols <- c("coral", "blue", "goldenrod1")

# Plot
sc1 %>%
  ggplot( aes(x=day, y=RLU, group=treatment, color=treatment)) +
    geom_line(lwd=1) +
    geom_point() +
    labs(x = "Day",
       y = "Cell Density (cells/mL)",
       color = "Treatment") + 
  scale_y_log10(breaks = c(3E6, 1E7, 3E7, 1E8, 3E8), labels = c("3e6", "1e7", "3e7", "1e8", "3e8")) +
  scale_color_manual(values = cols) +
  theme_light()

`````````

Figure 1. Growth curve of swimming *C. bombi* WH Nluc cells without exines (blue), 320 mg/mL sunflower (SF) exines (yellow), and 320 mg/mL buckwheat (BW) exines (orange) from day 0 to 3 measured on one plate and normalized using equation from each dilution series trendline. Note the difference in cell growth between the groups between the treatments, with the exine treatments showing more swimming cells. This could be explained by the exines settling at the bottom of the dish and not allowing as many cells to adhere, causing higher counts of swimming cells. 


<br>


> The data show no decrease in swimming cell growth when treated with either BW and SF exine media, leading to the conclusion that SF exines do not have an effect on swimming cell growth in *in vitro* models.










